
package sv.com.fpalacio.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteService", targetNamespace = "http://service.soap.fpalacio.com.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCliente", targetNamespace = "http://service.soap.fpalacio.com.sv/", className = "sv.com.fpalacio.soap.service.ObtenerCliente")
    @ResponseWrapper(localName = "obtenerClienteResponse", targetNamespace = "http://service.soap.fpalacio.com.sv/", className = "sv.com.fpalacio.soap.service.ObtenerClienteResponse")
    @Action(input = "http://service.soap.fpalacio.com.sv/ClienteService/obtenerClienteRequest", output = "http://service.soap.fpalacio.com.sv/ClienteService/obtenerClienteResponse")
    public String obtenerCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
